SELECT
    YEAR(S.SALES_DATE) AS YEAR, 
    MONTH(S.SALES_DATE) AS MONTH, 
    I.GENDER, 
    COUNT(DISTINCT USER_ID) AS USERS
FROM USER_INFO AS I
INNER JOIN ONLINE_SALE AS S USING (USER_ID)
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;