SELECT 
    REST_INFO.FOOD_TYPE, 
    REST_INFO.REST_ID, 
    REST_INFO.REST_NAME, 
    REST_INFO.FAVORITES
FROM REST_INFO
INNER JOIN (
    SELECT 
        FOOD_TYPE, 
        MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) NEWTABLE USING (FOOD_TYPE)
WHERE FAVORITES = NEWTABLE.MAX_FAVORITES
ORDER BY FOOD_TYPE DESC;