WITH RECURSIVE CTE (N) AS
(
    SELECT 0
    UNION ALL
    SELECT N + 1 FROM CTE
    WHERE N < 23
)

SELECT
    CTE.N AS HOUR, 
    COUNT(ANIMAL_ID) AS COUNT
FROM CTE
LEFT JOIN ANIMAL_OUTS
    ON CTE.N = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY N
ORDER BY N ASC;