SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
    ) NEWTABLE
INNER JOIN FOOD_PRODUCT USING(CATEGORY)
WHERE PRICE = MAX_PRICE
ORDER BY PRICE DESC;