SELECT
    AUTHOR_ID, 
    AUTHOR_NAME, 
    CATEGORY, 
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK AS B
INNER JOIN AUTHOR AS A USING (AUTHOR_ID)
INNER JOIN BOOK_SALES AS S USING(BOOK_ID)
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;