SELECT
    PRODUCT_ID, 
    PRODUCT_NAME, 
    SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
INNER JOIN FOOD_ORDER AS O USING (PRODUCT_ID)
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC, 
    PRODUCT_ID ASC;