SELECT
    APNT_NO, 
    PT_NAME, 
    PT_NO, 
    A.MCDP_CD, 
    DR_NAME, 
    APNT_YMD
FROM APPOINTMENT AS A
INNER JOIN PATIENT AS P USING (PT_NO)
INNER JOIN DOCTOR AS D
    ON A.MDDR_ID = D.DR_ID
WHERE
    APNT_CNCL_YN = 'N'
    AND APNT_YMD LIKE '2022-04-13%'
ORDER BY APNT_YMD ASC;